// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dwzfqzebhzchudbelqqf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImR3emZxemViaHpjaHVkYmVscXFmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDExMjI5NDUsImV4cCI6MjA1NjY5ODk0NX0.nn9Kni4oe8KtTaViv2ysy73wnydhkVyWg55A7r4yr4U";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);